// Package browserprivateconvert supports an explicitly selected, unencrypted
// private key in the local Workbench. It never accepts a PFX or plaintext
// private-key output and does not store anything in the instance inventory.
package browserprivateconvert

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/subtle"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"strings"

	"github.com/denyfirst/rootwell/internal/keymatch"
	"github.com/denyfirst/rootwell/internal/limits"
	"github.com/youmark/pkcs8"
)

const SchemaVersion = "rootwell.browser.private-convert.v1"

var (
	ErrInvalid  = errors.New("private key cannot be converted")
	ErrPassword = errors.New("output password does not meet policy")
)

// Summary contains no private key, raw key bytes, or input filename.
type Summary struct {
	InputFormat       string `json:"input_format"`
	Algorithm         string `json:"algorithm"`
	Bits              int    `json:"bits"`
	Curve             string `json:"curve"`
	PublicFingerprint string `json:"public_fingerprint"`
}

// Inspect accepts the same strict 64 KiB unencrypted PKCS#8, PKCS#1, and
// SEC1 PEM/DER parser used for certificate/key matching. It does not assess
// certificate trust or key strength.
func Inspect(input []byte) (Summary, error) {
	var result Summary
	err := keymatch.WithPrivateKey(input, func(key any, encoding keymatch.Encoding) error {
		var err error
		result, err = summarize(key, encoding)
		return err
	})
	if err != nil {
		return Summary{}, ErrInvalid
	}
	return result, nil
}

// ExportEncrypted reparses one immutable source, binds it to the exact public
// fingerprint shown by Inspect, and emits only password-encrypted PKCS#8 PEM.
// The caller must clear the returned bytes after requesting a download.
func ExportEncrypted(input []byte, expected string, password []byte) ([]byte, string, error) {
	if !validPassword(password) {
		return nil, "", ErrPassword
	}
	if !validFingerprint(expected) || len(input) == 0 || int64(len(input)) > limits.MaxPrivateKeyBytes {
		return nil, "", ErrInvalid
	}
	var output []byte
	err := keymatch.WithPrivateKey(input, func(key any, encoding keymatch.Encoding) error {
		metadata, err := summarize(key, encoding)
		if err != nil || len(metadata.PublicFingerprint) != len(expected) ||
			subtle.ConstantTimeCompare([]byte(metadata.PublicFingerprint), []byte(expected)) != 1 {
			return ErrInvalid
		}
		options := &pkcs8.Opts{
			Cipher: pkcs8.AES256CBC,
			KDFOpts: pkcs8.PBKDF2Opts{
				SaltSize: 16, IterationCount: 600_000, HMACHash: crypto.SHA256,
			},
		}
		der, err := pkcs8.MarshalPrivateKey(key, password, options)
		if err != nil || len(der) == 0 || len(der) > 64<<10 {
			clear(der)
			return ErrInvalid
		}
		defer clear(der)
		// This decoder reads only the bounded output generated by the fixed
		// options above, never an attacker-supplied encrypted input.
		checked, err := pkcs8.ParsePKCS8PrivateKey(der, password)
		if err != nil {
			return ErrInvalid
		}
		defer keymatch.ClearParsedKey(checked)
		verified, err := summarize(checked, keymatch.EncodingPKCS8DER)
		if err != nil || verified.PublicFingerprint != metadata.PublicFingerprint {
			return ErrInvalid
		}
		output = pem.EncodeToMemory(&pem.Block{Type: "ENCRYPTED PRIVATE KEY", Bytes: der})
		if len(output) == 0 || len(output) > 96<<10 {
			clear(output)
			output = nil
			return ErrInvalid
		}
		return nil
	})
	if err != nil {
		clear(output)
		return nil, "", ErrInvalid
	}
	var nonce [16]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		clear(output)
		return nil, "", ErrInvalid
	}
	fragment := strings.ToLower(strings.ReplaceAll(expected, ":", "")[:16])
	return output, "rootwell-encrypted-key-" + fragment + "-" + hex.EncodeToString(nonce[:]) + ".pem", nil
}

func summarize(key any, encoding keymatch.Encoding) (Summary, error) {
	signer, ok := key.(crypto.Signer)
	if !ok {
		return Summary{}, ErrInvalid
	}
	public := signer.Public()
	spki, err := x509.MarshalPKIXPublicKey(public)
	if err != nil {
		return Summary{}, ErrInvalid
	}
	defer clear(spki)
	digest := sha256.Sum256(spki)
	parts := make([]string, len(digest))
	for i, octet := range digest {
		parts[i] = strings.ToUpper(hex.EncodeToString([]byte{octet}))
	}
	result := Summary{InputFormat: string(encoding), PublicFingerprint: strings.Join(parts, ":")}
	switch value := public.(type) {
	case *rsa.PublicKey:
		result.Algorithm, result.Bits = "RSA", value.N.BitLen()
	case *ecdsa.PublicKey:
		result.Algorithm, result.Bits, result.Curve = "ECDSA", value.Curve.Params().BitSize, value.Curve.Params().Name
	case ed25519.PublicKey:
		result.Algorithm, result.Bits = "Ed25519", len(value)*8
	default:
		return Summary{}, ErrInvalid
	}
	return result, nil
}

func validPassword(value []byte) bool {
	if len(value) < 20 || len(value) > 128 {
		return false
	}
	for _, character := range value {
		if character < 0x21 || character > 0x7e {
			return false
		}
	}
	return true
}

func validFingerprint(value string) bool {
	if len(value) != 95 {
		return false
	}
	for index, character := range value {
		if index%3 == 2 {
			if character != ':' {
				return false
			}
		} else if character < '0' || character > '9' && (character < 'A' || character > 'F') {
			return false
		}
	}
	return true
}
